import sqlite3
conn=sqlite3.connect('library3.db')
print("NEW DATABASE CREATED")
#question1:-
#conn.execute("drop table title"
conn.execute('''CREATE TABLE BOOKS(BOOKID INT PRIMARY KEY NOT NULL,TITLEID INT NOT NULL, LOCATION TEXT NOT NULL, GENRE TEXT NOT NULL);''')
conn.execute('''CREATE TABLE TITLE(TITLEID INT  NOT NULL,TITLE TEXT NOT NULL, ISBN TEXT NOT NULL, PUBLISHERID INT  NOT NULL,PUBLISHERYEAR INT NOT NULL);''')
conn.execute('''CREATE TABLE AUTHORTITLE(AUTHORTITLEID INT  NOT NULL,AUTHORID INT NOT NULL,TITLEID INT NOT NULL);''')
conn.execute('''CREATE TABLE PUBLISHERS(PUBLISHERID INT  NOT NULL,NAME TEXT NOT NULL, STREETADDR TEXT NOT NULL, SUITENO INT  NOT NULL,ZIPCODEID INT NOT NULL);''')
conn.execute('''CREATE TABLE AUTHORS(AUTHORID INT  NOT NULL,FNAME TEXT NOT NULL, MNAME TEXT NOT NULL, LNAME TEXT  NOT NULL);''')
conn.execute('''CREATE TABLE ZIPCODES(ZIPCODEID INT  NOT NULL,CITY TEXT NOT NULL,STATE TEXT NOT NULL, ZIPCODE INT  NOT NULL);''')

print("ALL TABLES CREATED")
#question2:-
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (45,33,'pune','thriller'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (44,23,'shimla','comedy'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (55,44,'China','comedy'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (74,13,'nepal','romantic'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (85,32,'bhutan','inspiration'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (102,29,'chille','romantic'); ''')


conn.execute('''INSERT INTO TITLE(TITLEID,TITLE,ISBN,PUBLISHERID,PUBLISHERYEAR) VALUES (78,'born to blosom',90,'89',2014); ''')
conn.execute('''INSERT INTO TITLE(TITLEID,TITLE,ISBN,PUBLISHERID,PUBLISHERYEAR) VALUES (778,'wings of fire',95,'49',2000); ''')


conn.execute('''INSERT INTO AUTHORTITLE(AUTHORTITLEID,AUTHORID,TITLEID) VALUES (78,45,90); ''')
conn.execute('''INSERT INTO AUTHORTITLE(AUTHORTITLEID,AUTHORID,TITLEID) VALUES (110,45,78); ''')

conn.execute('''INSERT INTO PUBLISHERS(PUBLISHERID,NAME,STREETADDR,SUITENO,ZIPCODEID) VALUES (7,'evergreen','ASDFG',45,9000); ''')
conn.execute('''INSERT INTO PUBLISHERS(PUBLISHERID,NAME,STREETADDR,SUITENO,ZIPCODEID) VALUES (70,'selfstudy','QWERTYASDFG',455,90500); ''')

conn.execute('''INSERT INTO AUTHORS(AUTHORID,FNAME,MNAME,LNAME) VALUES (454,'robin','','sharma'); ''')
conn.execute('''INSERT INTO AUTHORS(AUTHORID,FNAME,MNAME,LNAME) VALUES (74,'dale','','carnage'); ''')

conn.execute('''INSERT INTO ZIPCODES(ZIPCODEID,CITY,STATE,ZIPCODE) VALUES (15654,'pune','maharastera',741852); ''')
conn.execute('''INSERT INTO ZIPCODES(ZIPCODEID,CITY,STATE,ZIPCODE) VALUES (64785,'Shimla','HP',52); ''')

cursor=conn.execute("SELECT * FROM BOOKS;")
for row in cursor:
    print("BOOKID= ", row[0])
    print("TITLE= ", row[1])
    print("LOCATION= ", row[2])
    print("GENRE= ", row[3])
    print("")

#questio3
print("questin3")
conn.execute("UPDATE BOOKS SET LOCATION ='spain' WHERE BOOKID = '102';")
conn.execute("UPDATE BOOKS SET LOCATION ='brazil' WHERE BOOKID = '85';")
cursor=conn.execute("SELECT * FROM BOOKS;")
for row in cursor:
    print("BOOKID= ", row[0])
    print("TITLE= ", row[1])
    print("LOCATION= ", row[2])
    print("GENRE= ", row[3])
    print("")